### PR TITLE
fix(diary): Fixes wrong computation of total duration

### LINKED ISSUE #386: Opening a page of the LearningDiary ends in 500
When opening a page of the learning diary via `Dashboard` -> `Page` the production server throws a 500 error (for all pages of some users).

E.g. clicking one of these entries:
Image

The production system prints the following error log:
```
nm-self-learning-1  | Error occurred during query execution:
nm-self-learning-1  | ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(0), cause: Some(Error { kind: ConversionError("Unable to fit integer value '4798658790' into an INT4 (32-bit signed integer)."), original_code: None, original_message: None }) }), transient: false })
nm-self-learning-1  |     at $n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7505)
nm-self-learning-1  |     at $n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:6623)
nm-self-learning-1  |     at $n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6307)
nm-self-learning-1  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/chunks/1896.js:8:69377
nm-self-learning-1  |     at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:130:8000)
nm-self-learning-1  |     at async s (/app/dist/apps/site/.next/server/chunks/1896.js:8:68534)
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/pages/learning-diary/page/[pageId].js:1:1663
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/chunks/1896.js:1:7149
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/chunks/1896.js:1:7412 {
nm-self-learning-1  |   clientVersion: '5.22.0'
nm-self-learning-1  | }
nm-self-learning-1  |  ⨯ PrismaClientUnknownRequestError:
nm-self-learning-1  | Invalid `prisma.learningDiaryPage.update()` invocation:
nm-self-learning-1  |
nm-self-learning-1  |
nm-self-learning-1  | Error occurred during query execution:
nm-self-learning-1  | ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(0), cause: Some(Error { kind: ConversionError("Unable to fit integer value '4798658790' into an INT4 (32-bit signed integer)."), original_code: None, original_message: None }) }), transient: false })
nm-self-learning-1  |     at $n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7505)
nm-self-learning-1  |     at $n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:6623)
nm-self-learning-1  |     at $n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6307)
nm-self-learning-1  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/chunks/1896.js:8:69377
nm-self-learning-1  |     at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:130:8000)
nm-self-learning-1  |     at async s (/app/dist/apps/site/.next/server/chunks/1896.js:8:68534)
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/pages/learning-diary/page/[pageId].js:1:1663
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/chunks/1896.js:1:7149
nm-self-learning-1  |     at async /app/dist/apps/site/.next/server/chunks/1896.js:1:7412 {
nm-self-learning-1  |   clientVersion: '5.22.0'
nm-self-learning-1  | }
```

### PR DESCRIPTION
**Pull request by Elscha**
This contains 2 fixes and 1 improvement:
- Fix: Correct computation of total duration: Computes the duration per resource and per change. So if Resource A, Resource B, and again Resource A are learned, two durations for A are computed and sumed up to a total duration. This is done to:
  - Not consider breaks between Resource changes
  - Not computing the duration of Resource A twice
- Fix: Checks if endDate of a diary Page is later than 6 hours after start (was requirement by Psychology). If yes the endDate is adjusted to avoid consideration of events of shorter lesson visists, for which no DiaryPage is created (less than 1 minute). 
- Improvement: Metric moved to `analysis` to facilitate re-use.

Fixes #386

### CODE REVIEW

File: libs/feature/diary/src/lib/access-learning-diary.ts [hunk 1]
```diff
@@ -75,12 +76,23 @@ async function updateDiaryDetails(username: string, id: string, endDate: Date) {
 			return;
 		}
 
+		const SIX_HOURS_IN_MS = 6 * 60 * 60 * 1000;
```
Comment (spark-sse) [inline libs/feature/diary/src/lib/access-learning-diary.ts:79]: hier gerne date-fns benutzen um magic numbers zu vermeiden. 

```suggestion

	const SIX_HOURS_MS = hoursToMilliseconds(6);
```

File: libs/feature/diary/src/lib/access-learning-diary.ts [hunk 2]
```diff
@@ -75,12 +76,23 @@ async function updateDiaryDetails(username: string, id: string, endDate: Date) {
...
+		// Diary should span at max 6 hours (= SIX_HOURS_IN_MS)
+		// Maybe there are single events (visits) of a lesson for which no diary page was created,
+		// i.e., visit was shorter than 1 minute. We do not want to consider these events.
+		const start = diaryMeta.createdAt.getTime();
+		const end = endDate.getTime();
+		if (end - start > SIX_HOURS_IN_MS) {
+			endDate = new Date(diaryMeta.createdAt.getTime() + SIX_HOURS_IN_MS);
+		}
```
Comment (spark-sse) [inline libs/feature/diary/src/lib/access-learning-diary.ts:87]: auch hier date-fns nutzen

File: libs/feature/analysis/src/lib/metrics/learning-duration.ts [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+			// Start new segment
+			segmentStart = event.createdAt;
+			currentResource = event.resourceId;
+		}
+	}
+
+	// Add duration for the final segment
+	const lastEvent = events[events.length - 1];
+	const lastDuration = lastEvent.createdAt.getTime() - segmentStart.getTime();
```
Comment (spark-sse) [inline libs/feature/analysis/src/lib/metrics/learning-duration.ts:37]: hier  könnte `differenceInMilliseconds` die lesbarkeit erhöhen

**Review by spark-sse — CHANGES_REQUESTED** [review]
